# Generated by Django 4.2.5 on 2024-08-20 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255)),
                ('is_subcategory', models.BooleanField(default=False)),
                ('category_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('in_merchant', models.CharField(max_length=64, null=True)),
                ('in_terminal', models.CharField(max_length=64, null=True)),
                ('in_terminal_account', models.CharField(max_length=128, null=True)),
                ('percentage', models.FloatField(default=0.0, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Epos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_id', models.CharField(max_length=30, verbose_name='Terminal ID')),
                ('merchant_id', models.CharField(max_length=20, verbose_name='Merchant ID')),
                ('state', models.IntegerField(default=0, verbose_name='State')),
                ('type', models.IntegerField(default=0)),
                ('pc_type', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Epos status')),
                ('status', models.IntegerField(default=0)),
                ('purpose', models.CharField(max_length=30, null=True, verbose_name='Purpose of Usage')),
                ('account', models.CharField(max_length=45, null=True, verbose_name='Account Number ')),
                ('point_code', models.CharField(max_length=30, null=True, verbose_name='Point Code')),
                ('commission', models.FloatField(default=0.0, verbose_name='Commission for EPOS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_short', models.CharField(max_length=255)),
                ('provider_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransactionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_id', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('amount', models.BigIntegerField()),
                ('expire', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('option', models.CharField(choices=[('WalletToCard', 'wallet-to-card'), ('WalletToEpos', 'wallet-to-epos'), ('EposToWallet', 'epos-to-wallet'), ('CardToWallet', 'card-to-wallet')], max_length=55)),
                ('context', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WalletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=255, null=True)),
                ('expire', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferW2WModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('wallet_to_epos', models.CharField(blank=True, max_length=255, null=True)),
                ('epos_to_wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('wallet_to_epos_status', models.BooleanField(default=False)),
                ('epos_to_wallet_status', models.BooleanField(default=False)),
                ('wallet_to_epos_id', models.IntegerField(blank=True, null=True)),
                ('epos_to_wallet_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='wallet.walletmodel')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='wallet.walletmodel')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TransactionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_tr_id', models.CharField(max_length=255, unique=True)),
                ('sender', models.CharField(max_length=255)),
                ('expire', models.CharField(blank=True, max_length=255, null=True)),
                ('db_amount', models.BigIntegerField()),
                ('sender_ext_id', models.CharField(blank=True, max_length=255, null=True)),
                ('db_rrn', models.CharField(max_length=255, null=True)),
                ('db_state', models.IntegerField()),
                ('db_description', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=255)),
                ('receiver_owner', models.CharField(max_length=50)),
                ('cr_tr_id', models.CharField(max_length=255, unique=True)),
                ('cr_rrn', models.CharField(max_length=255, null=True)),
                ('cr_state', models.IntegerField()),
                ('cr_description', models.CharField(max_length=100)),
                ('cr_ext_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cr_amount', models.BigIntegerField()),
                ('card_to_card', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('sender_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='provider_images/')),
                ('providers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wallet.providers')),
            ],
        ),
        migrations.CreateModel(
            name='PaynetSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(null=True)),
                ('provider_id', models.IntegerField(null=True)),
                ('service_id', models.IntegerField(null=True)),
                ('fields', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='category_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wallet.category')),
            ],
        ),
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=255)),
                ('expire', models.CharField(max_length=255)),
                ('card_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('type', models.CharField(choices=[('physical', 'physical'), ('virtual', 'virtual')], default='physical', max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('balance', models.IntegerField(default=0)),
                ('mask', models.CharField(blank=True, max_length=255, null=True)),
                ('bank', models.CharField(blank=True, max_length=255, null=True)),
                ('card_owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pc_type', models.IntegerField(blank=True, default=0, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'card_number')},
            },
        ),
        migrations.CreateModel(
            name='BalanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.cardmodel')),
            ],
        ),
    ]
