# Generated by Django 4.2.5 on 2024-08-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_commission_in_terminal_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='in_terminal_account',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='out_merchant',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='out_terminal',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='out_terminal_account',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
