# Generated by Django 4.2.5 on 2024-09-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_commission_in_terminal_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerimage',
            name='providers',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(default=1, upload_to='image/category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='provider_images/'),
        ),
        migrations.AlterField(
            model_name='transactionsmodel',
            name='cr_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionsmodel',
            name='cr_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactionsmodel',
            name='cr_rrn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionsmodel',
            name='cr_state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionsmodel',
            name='db_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactionsmodel',
            name='db_state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionsmodel',
            name='receiver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionsmodel',
            name='receiver_owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='CategoryImage',
        ),
        migrations.DeleteModel(
            name='ProviderImage',
        ),
    ]
