# Generated by Django 4.2.5 on 2024-09-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='card_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
