# Generated by Django 4.2.5 on 2024-09-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_cardmodel_card_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsmodel',
            name='payment_type',
            field=models.CharField(choices=[('card', 'Card Payment'), ('oplata', 'Oplata')], default='card', help_text='Choose the type of payment, either card payment or oplata.', max_length=10),
        ),
    ]
