# Generated by Django 4.2.5 on 2024-10-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_alter_transactionsmodel_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsmodel',
            name='db_rrn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
