# Generated by Django 4.2.5 on 2024-10-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_transactionsmodel_credit_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsmodel',
            name='commision',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
