# Generated by Django 4.2.5 on 2024-10-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_transactionsmodel_cr_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='ref_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
