# Generated by Django 4.2.5 on 2024-10-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_cardmodel_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='providers',
            name='image',
        ),
    ]
