# Generated by Django 4.2.5 on 2024-10-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_category_image_providers_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='providers',
            name='image',
        ),
    ]
