# Generated by Django 4.2.5 on 2024-10-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_remove_category_image_remove_providers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
