# Generated by Django 4.2.5 on 2024-10-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0027_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Notification Message'),
        ),
    ]
