# Generated by Django 4.2.5 on 2024-10-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0029_notificationmodel_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
