# Generated by Django 4.2.5 on 2024-10-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0030_alter_notificationmodel_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationModel',
        ),
    ]
