# Generated by Django 4.2.5 on 2024-10-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0031_delete_notificationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(blank=True, max_length=255, null=True)),
                ('card_number', models.CharField(blank=True, max_length=255, null=True)),
                ('card_mask', models.CharField(blank=True, max_length=255, null=True)),
                ('pc_type', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
