# Generated by Django 4.2.5 on 2024-10-31 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0032_receivercardmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivercardmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
