# Generated by Django 4.2.5 on 2024-10-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0034_receivercardmodel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivercardmodel',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
