# Generated by Django 4.2.5 on 2024-11-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0037_alter_transactionsmodel_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
